
// script.js

const questions = [
  { key: "eta", text: "Quanti anni hai?" },
  { key: "sesso", text: "Sei di sesso maschile o femminile?" },
  { key: "origine_etnica", text: "Qual è la tua origine etnica?" },
  { key: "altezza", text: "Qual è la tua altezza (in cm)?" },
  { key: "peso", text: "Qual è il tuo peso (in kg)?" },
  { key: "giro_vita", text: "La misura del tuo giro vita è maggiore di 88 cm (donna) o 102 cm (uomo)?" },
  { key: "glicemia", text: "La tua glicemia è inferiore a 100 mg/dl?" },
  { key: "colesterolo_totale", text: "Qual è il tuo colesterolo totale (mg/dl)?" },
  { key: "colesterolo_ldl", text: "Il tuo colesterolo LDL supera 70 mg/dl?" },
  { key: "colesterolo_hdl", text: "Il tuo colesterolo HDL è inferiore a 50 (donna) o 40 (uomo)?" },
  { key: "pressione", text: "La tua pressione è inferiore a 130/85 mmHg?" },
  { key: "malattie_croniche", text: "Hai malattie croniche diagnosticate?" },
  { key: "farmaci", text: "Assumi farmaci?" },
  { key: "farmaci_dettaglio", text: "Se sì, elencali." },
  { key: "interventi", text: "Hai subito interventi chirurgici rilevanti?" },
  { key: "interventi_dettaglio", text: "Se sì, elencali." },
  { key: "familiarita_tumori", text: "Ci sono casi di tumori in famiglia?" },
  { key: "sede_tumore", text: "In quale sede ha avuto il tumore il tuo famigliare?" },
  { key: "fumatore", text: "Fumi?" },
  { key: "n_sigarette", text: "Quante sigarette fumi al giorno?" },
  { key: "alcol", text: "Consumi alcolici?" },
  { key: "unita_alcoliche", text: "Quante unità alcoliche al giorno?" },
  { key: "attivita_fisica", text: "Fai attività fisica?" },
  { key: "tipo_attivita", text: "Che tipo di attività svolgi?" },
  { key: "durata_attivita", text: "Quanto dura ogni allenamento (minuti)?" },
  { key: "alimentazione", text: "Com'è la tua alimentazione?" },
  { key: "stanchezza", text: "Ti senti stanco/a frequentemente?", condition: (a) => a.eta >= 65 },
  { key: "scale", text: "Riesci a salire una rampa di scale?", condition: (a) => a.eta >= 65 },
  { key: "camminata", text: "Riesci a camminare per 100 metri?", condition: (a) => a.eta >= 65 },
  { key: "malattie_multiple", text: "Hai più di 5 malattie croniche?", condition: (a) => a.eta >= 65 },
  { key: "perdita_peso", text: "Hai perso più di 5kg involontariamente nell'ultimo anno?", condition: (a) => a.eta >= 65 },
  { key: "sollevamento", text: "Hai difficoltà a sollevare oggetti pesanti?", condition: (a) => a.eta >= 65 },
  { key: "alzarsi_sedia", text: "Hai problemi ad alzarti da una sedia?", condition: (a) => a.eta >= 65 },
  { key: "cadute", text: "Hai avuto cadute frequenti?", condition: (a) => a.eta >= 65 },
  { key: "debolezza", text: "Ti senti debole?", condition: (a) => a.eta >= 65 },
  { key: "eta_menarca", text: "Quanti anni avevi al primo ciclo mestruale?", condition: (a) => a.sesso === "femminile" },
  { key: "contraccettivi", text: "Hai mai usato contraccettivi ormonali?", condition: (a) => a.sesso === "femminile" },
  { key: "gravidezza", text: "Hai avuto gravidanze?", condition: (a) => a.sesso === "femminile" },
  { key: "eta_menopausa", text: "A che età hai avuto la menopausa? (facoltativo)", condition: (a) => a.sesso === "femminile" },
  { key: "familiarita_seno", text: "Tua madre o nonna hanno avuto tumore al seno?", condition: (a) => a.sesso === "femminile" },
  { key: "screening_seno", text: "Hai mai fatto mammografia o ecografia mammaria?", condition: (a) => a.sesso === "femminile" && a.eta >= 25 },
  { key: "papsmear", text: "Svolgi regolarmente il Pap test?", condition: (a) => a.sesso === "femminile" && a.eta >= 25 }
];

export { questions };
