/**
 * Canonical fixture set for score equivalence + unit testing.
 *
 * Each case is hand-picked to span:
 *   - typical adult cases with no/some/many risk factors
 *   - edge cases at the boundaries of validated ranges
 *   - sex-specific paths (male vs female SCORE2 coefficients)
 *
 * Expected values must be regenerated by running the LEGACY engine on each
 * fixture once, and pinning the resulting numbers here. This file is the
 * regression baseline for clinical correctness.
 */

import type { AssessmentInput } from '../../shared/types/clinical';

export interface ScoreCase {
  name: string;
  input: AssessmentInput;
  expected: {
    score2?: { value: number; band: string };
    score2Diabetes?: { value: number; band: string };
    ada?: { value: number; band: string };
    fli?: { value: number; band: string };
    frail?: { value: number; band: string };
    bmi?: { value: number; category: string };
    metSyndrome?: { count: number; positive: boolean };
    fib4?: { value: number; band: string };
    egfr?: { value: number; ckdStage: string };
    predimed?: { score: number; category: string };
  };
}

export const SCORE_CASES: ScoreCase[] = [
  {
    name: 'low-risk-young-male-non-smoker',
    input: {
      patient: { age: 42, sex: 'male' },
      vitals: {
        systolicBp: 120,
        bmi: 23.4,
        waistCm: 84,
        weightKg: 76,
        heightCm: 180,
      },
      labs: {
        totalCholesterolMmolL: 4.5,
        hdlCholesterolMmolL: 1.4,
        triglyceridesMmolL: 1.0,
        glucoseFastingMgDl: 90,
        gammaGtUL: 22,
        creatinineMgDl: 0.9,
        astUL: 22,
        altUL: 25,
        plateletsThousandPerUL: 250,
      },
      lifestyle: { smokingStatus: 'never', alcoholUnitsPerWeek: 2 },
      activity: { minutesPerWeek: 220 },
      conditions: { diabetes: false, hypertension: false, ckd: false, cvd: false },
      // Expected values are placeholders — populate after running LEGACY engine
      // on this fixture. Tests will compare new engine ≡ legacy engine ≡ this expected.
    },
    expected: {
      bmi:       { value: 23.4,  category: 'normal' },
      egfr:      { value: 100,   ckdStage: 'G1' },
      // score2/ada/etc populated post-baseline run
    },
  },
  {
    name: 'high-risk-male-smoker-hypertensive',
    input: {
      patient: { age: 62, sex: 'male' },
      vitals: { systolicBp: 168, bmi: 31.4, waistCm: 108, weightKg: 102, heightCm: 180 },
      labs: {
        totalCholesterolMmolL: 6.5,
        hdlCholesterolMmolL: 0.95,
        triglyceridesMmolL: 2.6,
        glucoseFastingMgDl: 118,
        gammaGtUL: 60,
        creatinineMgDl: 1.3,
        astUL: 38,
        altUL: 45,
        plateletsThousandPerUL: 210,
      },
      lifestyle: { smokingStatus: 'current', alcoholUnitsPerWeek: 14 },
      activity: { minutesPerWeek: 30 },
      conditions: { diabetes: false, hypertension: true, ckd: false, cvd: false },
    },
    expected: {
      bmi:       { value: 31.4,  category: 'obese_I' },
    },
  },
  {
    name: 'female-diabetic-postmenopausal',
    input: {
      patient: { age: 58, sex: 'female' },
      vitals: { systolicBp: 142, bmi: 29.1, waistCm: 96, weightKg: 78, heightCm: 164 },
      labs: {
        totalCholesterolMmolL: 5.8,
        hdlCholesterolMmolL: 1.2,
        triglyceridesMmolL: 1.9,
        glucoseFastingMgDl: 156,
        hba1cPercent: 7.2,
        gammaGtUL: 45,
        creatinineMgDl: 0.95,
        astUL: 30,
        altUL: 36,
        plateletsThousandPerUL: 240,
      },
      lifestyle: { smokingStatus: 'former', alcoholUnitsPerWeek: 3 },
      activity: { minutesPerWeek: 90 },
      conditions: { diabetes: true, hypertension: true, ckd: false, cvd: false },
    },
    expected: {
      bmi: { value: 29.1, category: 'overweight' },
    },
  },
  {
    name: 'edge-very-old-male-frail',
    input: {
      patient: { age: 84, sex: 'male' },
      vitals: { systolicBp: 138, bmi: 21.0, waistCm: 88, weightKg: 64, heightCm: 174 },
      labs: {
        totalCholesterolMmolL: 4.1,
        hdlCholesterolMmolL: 1.1,
        triglyceridesMmolL: 1.4,
        glucoseFastingMgDl: 102,
        creatinineMgDl: 1.6,
        astUL: 28,
        altUL: 22,
        plateletsThousandPerUL: 180,
      },
      lifestyle: { smokingStatus: 'never', alcoholUnitsPerWeek: 0 },
      activity: { minutesPerWeek: 30 },
      frail: {
        fatigue: true,
        resistance: true,
        ambulation: false,
        illnesses: 4,
        lossOfWeight: false,
      },
      conditions: { diabetes: false, hypertension: true, ckd: true, cvd: false },
    },
    expected: {
      bmi:   { value: 21.0, category: 'normal' },
      frail: { value: 3, band: 'pre-frail' },
    },
  },
];
